name: Production Deploy
on:
  workflow_dispatch:
    inputs:
      master_image:
        required: true
        description: 'Image:'
      release_tag:
        required: true
        description: 'Release Tag:'
      release_title:
        required: true
        description: 'Release Tag:'
      release_body:
        required: false
        description: 'Release Body:'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Parse Inputs
      run: |
        echo "Image ${{ github.event.inputs.master_image }}"
        echo "Tag ${{ github.event.inputs.release_tag }}"
        printf "Body ${{ github.event.inputs.release_body }}"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: ${{ github.event.inputs.release_title }}
        body: |
          ${{ github.event.inputs.release_body }}
        draft: false
        prerelease: false
