name: Production Deploy
on:
  workflow_dispatch:
    inputs:
      master_image:
        required: true
        description: 'The full master image needed to deploy to production'
      release_tag:
        required: true
        description: tag to release for this deploy
      release_body:
        required: false
        description: 'Body field for the release tag'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Parse Inputs
      run: |
        echo "Image ${{ github.event.inputs.master_image }}"
        echo "Tag ${{ github.event.inputs.release_tag }}"
        printf "Body ${{ github.event.inputs.release_body }}"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: Release ${{ github.event.inputs.release_tag }}
        body: |
          ${{ github.event.inputs.release_body }}
        draft: false
        prerelease: false
      
      
