name: Production Deploy
on:
  workflow_dispatch:
    inputs:
      master_image:
        required: true
        description: 'The full master image needed to deploy to production'
      release_tag:
        required: true
        description: tag to release for this deploy
      release_body:
        required: false
        description: 'Body field for the release tag'

jobs:
  Parse:
    runs-on: ubuntu-latest
    steps:
    - name: Master Image
      run: echo "Image ${{ github.event.inputs.master_image }}"
    - name: Release Tag
      run: echo "Tag ${{ github.event.inputs.release_tag }}"
    - name: Release Body
      run: echo "Body ${{ github.event.inputs.release_body }}"
      
