
name: PR Url

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]


jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=REPO_NAME::${{ github.repository.name }}
      - name: test
        run: |
          echo Github-Pull_Request-Number: ${{ github.event.pull_request.number }}
          echo Github-Event-Action: ${{ github.event.action }}
          echo Github-Event_name: ${{ github.event_name }}
          echo Github-Repository: ${{ github.repository }}
          echo Github-Head_ref: ${{ github.head_ref }}
          echo Github-Pull_Request-Base-Repo-Name ${{ github.pull_request.base.repo.name }}
          echo Repo_Name: $REPO_NAME
          echo Github-Repository: ${{ github.repository }}
          echo Finished Now

      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}  
        
  
  
