
name: PR Url

on:
  pull_request:
    types: [opened, reopened]


jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.event.action }}
          echo ${{ github.event_name }}
          echo ${{ github.repository }}
          echo ${{ github.head_ref }}
          echo ${{ github.event}}
      - name: comment-pr
        uses: JoseThen/comment-pr@master
        with:
          comment: "PR Instance at https://${{ github.event.pull_request.number }}-pr.pineapples.dev"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  comment:
    runs-on: ubuntu-latest
    if: success() && (github.event_name == 'opened' || github.event_name == 'reopened')
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `https://${context.repo.repo}`
            })
