
name: PR Url
env:
  REPO_NAME: ${{ github.event.pull_request.base.name }}

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]



jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo github.event.pull_request.number: ${{ github.event.pull_request.number }}
          echo github.event.action: ${{ github.event.action }}
          echo Github-Event_name: ${{ github.event_name }}
          echo github.repository: ${{ github.repository }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.event.pull_request.base.repo.name: ${{ github.event.pull_request.base.repo.name }}
          echo REPO_NAME: $REPO_NAME
          echo Finished Now

      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}  
        
  
  
