
name: PR Url

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]


jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=REPO_NAME::${{ github.repository.name }}
      - name: test
        run: |
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.event.action }}
          echo ${{ github.event_name }}
          echo ${{ github.repository }}
          echo ${{ github.head_ref }}
          echo ${{ github.repository.name }}
          echo $REPO_NAME
          echo ${{ github.repository }}
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}  
        
  
  
