
name: PR Url

on:
  pull_request:
    types: [opened, reopened]


jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - name: comment-pr
        uses: JoseThen/comment-pr@master
        env:
            PR_NUM: ${{ github.event.pull_request.number }}
        with:
          comment: "PR Instance at $PR_NUM-pr.pineapples.dev"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
