
name: PR Url

on:
  pull_request:
    types: [opened, reopened]


jobs:
  pr-instance:
    runs-on: ubuntu-latest
    steps:
      - name: comment-pr
        uses: JoseThen/comment-pr@master
        with:
          comment: "PR Instance at `https://${{ github.event.pull_request.number }}-pr.pineapples.dev`"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
